"""Add remaining_cash to strategies

Revision ID: 4628673c6aac
Revises: b54de66b45bc
Create Date: 2025-10-09 00:18:02.621535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4628673c6aac'
down_revision: Union[str, None] = 'b54de66b45bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add column as nullable first
    op.add_column('strategies', sa.Column('remaining_cash', sa.Float(), nullable=True))
    
    # Set default value for existing rows
    op.execute('UPDATE strategies SET remaining_cash = 0.0 WHERE remaining_cash IS NULL')
    
    # Now make it NOT NULL
    op.alter_column('strategies', 'remaining_cash', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('strategies', 'remaining_cash')
    # ### end Alembic commands ###

