"""add_fundamental_data_fields

Revision ID: bd79edaec8a0
Revises: 7c8d9e0f1a2b
Create Date: 2025-10-09 14:23:08.753940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd79edaec8a0'
down_revision: Union[str, None] = '7c8d9e0f1a2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stocks', sa.Column('market_cap', sa.Float(), nullable=True))
    op.add_column('stocks', sa.Column('pe_ratio', sa.Float(), nullable=True))
    op.add_column('stocks', sa.Column('eps', sa.Float(), nullable=True))
    op.add_column('stocks', sa.Column('dividend_yield', sa.Float(), nullable=True))
    op.add_column('stocks', sa.Column('beta', sa.Float(), nullable=True))
    op.add_column('stocks', sa.Column('price_to_book', sa.Float(), nullable=True))
    op.add_column('stocks', sa.Column('price_to_sales', sa.Float(), nullable=True))
    op.add_column('stocks', sa.Column('roe', sa.Float(), nullable=True))
    op.add_column('stocks', sa.Column('debt_to_equity', sa.Float(), nullable=True))
    op.add_column('stocks', sa.Column('current_ratio', sa.Float(), nullable=True))
    op.add_column('stocks', sa.Column('quick_ratio', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stocks', 'quick_ratio')
    op.drop_column('stocks', 'current_ratio')
    op.drop_column('stocks', 'debt_to_equity')
    op.drop_column('stocks', 'roe')
    op.drop_column('stocks', 'price_to_sales')
    op.drop_column('stocks', 'price_to_book')
    op.drop_column('stocks', 'beta')
    op.drop_column('stocks', 'dividend_yield')
    op.drop_column('stocks', 'eps')
    op.drop_column('stocks', 'pe_ratio')
    op.drop_column('stocks', 'market_cap')
    # ### end Alembic commands ###

